from __future__ import annotations

import csv
import difflib
import io
import json
from collections import Counter
from pathlib import Path


LABELS = ["LOW", "MEDIUM", "HIGH"]
SEVERITY = {"LOW": 0.0, "MEDIUM": 0.5, "HIGH": 1.0}
DEFAULT_REASON = (
    "Model identified this clause as HIGH risk. The prediction should be reviewed by a legal professional."
)


def load_reference_patterns(root_dir: Path) -> list[dict]:
    """Load optional dataset explanations for reliable clause/pattern matches."""
    candidates = [
        root_dir.parent / "Dataset" / "legal_risk_dataset_full.csv",
        root_dir.parent / "Colab" / "best_model" / "legal_risk_dataset_full.csv",
        root_dir / "model" / "legal_risk_dataset_full.csv",
    ]

    rows: list[dict] = []
    for path in candidates:
        if not path.exists():
            continue
        with path.open("r", encoding="utf-8-sig", newline="") as handle:
            reader = csv.DictReader(handle)
            for row in reader:
                if row.get("clause_text") and row.get("risk_reason"):
                    rows.append(row)
        if rows:
            break
    return rows


def find_reason(clause_text: str, risk_label: str, references: list[dict]) -> dict:
    """Return a dataset-grounded reason only when a strong textual match exists."""
    if risk_label != "HIGH":
        return {
            "reason": "No explanation is generated by the model for this prediction.",
            "clause_type": "",
            "pattern_reference": "",
            "matched_reference": False,
        }

    best_row = None
    best_score = 0.0
    normalized_clause = _normalize(clause_text)

    for row in references:
        if row.get("risk_level", "").upper() != "HIGH":
            continue
        reference_text = _normalize(row.get("clause_text", ""))
        pattern = _normalize(row.get("pattern_reference", ""))
        text_score = difflib.SequenceMatcher(None, normalized_clause, reference_text).ratio()
        pattern_score = 0.0
        if pattern and pattern in normalized_clause:
            pattern_score = 0.93
        score = max(text_score, pattern_score)
        if score > best_score:
            best_score = score
            best_row = row

    if best_row and best_score >= 0.88:
        return {
            "reason": best_row.get("risk_reason") or DEFAULT_REASON,
            "clause_type": best_row.get("clause_type", ""),
            "pattern_reference": best_row.get("pattern_reference", ""),
            "matched_reference": True,
        }

    return {
        "reason": DEFAULT_REASON,
        "clause_type": "",
        "pattern_reference": "",
        "matched_reference": False,
    }


def summarize(results: list[dict]) -> dict:
    counts = Counter(item["predicted_risk"] for item in results)
    total = len(results)
    risk_score = 0.0
    if total:
        risk_score = sum(SEVERITY[item["predicted_risk"]] for item in results) / total
        high_ratio = counts["HIGH"] / total
        risk_score = min(1.0, risk_score + (0.15 * high_ratio))

    if counts["HIGH"] > 0 or risk_score >= 0.67:
        overall = "HIGH"
    elif counts["MEDIUM"] > 0 or risk_score >= 0.34:
        overall = "MEDIUM"
    else:
        overall = "LOW"

    return {
        "overall_risk": overall,
        "risk_score": round(risk_score, 4),
        "clauses_analyzed": total,
        "counts": {label: counts[label] for label in LABELS},
    }


def to_json_report(file_name: str, summary: dict, results: list[dict]) -> str:
    return json.dumps(
        {
            "file_name": file_name,
            "summary": summary,
            "clauses": results,
            "disclaimer": (
                "This is an AI/ML research prototype and does not provide legal advice. "
                "Predictions and confidence scores should not be treated as legal conclusions."
            ),
        },
        indent=2,
        ensure_ascii=False,
    )


def to_csv_report(results: list[dict]) -> str:
    output = io.StringIO()
    fieldnames = [
        "clause_id",
        "chunk_id",
        "was_chunked",
        "clause_text",
        "predicted_risk",
        "low_probability",
        "medium_probability",
        "high_probability",
        "confidence",
        "reason",
        "clause_type",
        "pattern_reference",
    ]
    writer = csv.DictWriter(output, fieldnames=fieldnames)
    writer.writeheader()
    for result in results:
        writer.writerow({key: result.get(key, "") for key in fieldnames})
    return output.getvalue()


def _normalize(text: str) -> str:
    return " ".join(text.lower().split())
